### ISSUE TITLE
decor.Spinner not working on python 3.6.6

### ISSUE THREAD

**Issue by fuzzball81** [release-depot/toolchest#17]
When using decor.Spinner in a python 3.6.6 environment I get the following error:

`line 75, in __init__
sys.stdout.write('\b' + self._spinner.next())
AttributeError: 'itertools.cycle' object has no attribute 'next'
`

Expected:
The spinner functions as expected without a stack trace.

**Comment by fuzzball81** [comment]
This was fixed by https://github.com/release-depot/toolchest/pull/20 Closing.
